- name: Launch sonarqube container
  docker_container:
    name: sonarqube
    image: sonarqube
    ports:
      - "9000:9000"
#   links:
#      - db
#    environment:
#      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
#    volumes_from:
#      - plugins
    volumes:
      - "/data/sonar/conf:/opt/sonarqube/conf"
      - "/data/sonar/data:/opt/sonarqube/data"
      - "/data/sonar/extensions:/opt/sonarqube/extensions"
      - "/data/sonar/plugins:/opt/sonarqube/lib/bundled-plugins"
  tags: [sonar]

#- name:
#  container_name: postgres
#  image: postgres
#  volumes_from:
#    - datadb
#  environment:
#   - POSTGRES_USER=sonar
#   - POSTGRES_PASSWORD=sonar

#datadb:
#  image: postgres
#  container_name: plugins_postgres
#  volumes:
#    - /var/lib/postgresql
#  command: /bin/true

#plugins:
#  container_name: plugins_sonarqube
#  image: sonarqube
#  volumes:
#   - /opt/sonarqube/extensions
#   - /opt/sonarqube/lib/bundled-plugins
#  command: /bin/true

